import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { workspacePath,executeTool,requiresApproval,availableTools,publicAddress,fetchPublicPage,runProcess } from '../electron/tools';
import type { Settings } from '../shared/types';
const signal=()=>new AbortController().signal;
async function fixture(t:any){const root=await fs.mkdtemp(path.join(os.tmpdir(),'orbit-test-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));return root;}
const settings=(workspace:string):Settings=>({workspace,provider:{kind:'demo',model:'demo',baseUrl:''},maxSteps:8,allowCommands:false,allowComputer:false,pythonPath:'python3'});
test('file paths reject traversal, absolute paths, credential files, and symlinks',async t=>{const root=await fixture(t);await fs.writeFile(path.join(root,'hello.txt'),'hello');assert.equal(await workspacePath(root,'hello.txt'),path.join(root,'hello.txt'));for(const p of ['../outside','/etc/passwd','.env','.env.local','.ssh/key'])await assert.rejects(workspacePath(root,p,true));await fs.symlink(os.tmpdir(),path.join(root,'linked'),process.platform==='win32'?'junction':'dir');await assert.rejects(workspacePath(root,'linked/secret',true),/Symbolic/);});
test('hard links cannot be written through file tools',async t=>{const root=await fixture(t);await fs.writeFile(path.join(root,'original'),'unchanged');await fs.link(path.join(root,'original'),path.join(root,'alias'));await assert.rejects(workspacePath(root,'alias',true),/Hard-linked/);});
test('nested write/read works, hidden credentials omitted from list',async t=>{const root=await fixture(t);const s=settings(root);await executeTool({id:'1',name:'write_file',arguments:{path:'docs/note.md',content:'# Hello'}},s,signal(),'');assert.equal((await executeTool({id:'2',name:'read_file',arguments:{path:'docs/note.md'}},s,signal(),'')).content,'# Hello');await fs.writeFile(path.join(root,'.env'),'TOKEN=secret');const listed=await executeTool({id:'3',name:'list_files',arguments:{path:'.'}},s,signal(),'');assert.ok(!listed.content.includes('.env'));});
test('disabled privileged tools cannot execute and all external effects require approvals',async t=>{const root=await fixture(t);for(const name of ['write_file','run_command','fetch_url','computer'])assert.ok(requiresApproval(name));assert.ok(!availableTools(settings(root)).some(t=>t.name==='computer'||t.name==='run_command'));await assert.rejects(executeTool({id:'1',name:'run_command',arguments:{command:'echo unsafe'}},settings(root),signal(),''),/disabled/);await assert.rejects(executeTool({id:'2',name:'computer',arguments:{action:'click',x:1,y:1}},settings(root),signal(),''),/disabled/);});
test('private network and URL credential requests are blocked',async()=>{for(const ip of ['127.0.0.1','10.1.1.1','192.168.2.1','169.254.169.254','172.20.0.1','100.64.0.1','::1','::ffff:127.0.0.1','fc00::1'])assert.equal(publicAddress(ip),false,ip);assert.equal(publicAddress('8.8.8.8'),true);await assert.rejects(fetchPublicPage('https://127.0.0.1/',signal()),/Private/);await assert.rejects(fetchPublicPage('https://user:secret@example.com/',signal()),/public HTTPS/);});
test('process cancellation terminates the task',async t=>{const root=await fixture(t);const controller=new AbortController();const pending=runProcess(process.execPath,['-e','setInterval(()=>{},1000)'],{cwd:root,signal:controller.signal});setTimeout(()=>controller.abort(),50);await assert.rejects(pending,/cancelled/);});
test('processes enforce output limits',async t=>{const root=await fixture(t);await assert.rejects(runProcess(process.execPath,['-e',"console.log('x'.repeat(4096))"],{cwd:root,signal:signal(),maxBytes:100}),/output exceeded/);});
